import './globals.css'
import Navigation from '@/components/Navigation'



export const metadata = {
  title: 'My first Next app',
  description: 'Generated by create next app',
  keywords: "next,react,app"
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
  <link rel='stylesheet' href='https://bootswatch.com/5/vapor/bootstrap.min.css'/>
</head>
      <body>
     <Navigation/>
     <div className='container p-4'> {children}</div>
    
     </body>
    </html>
  )
}
